version: '3'

services:
  my-postgres-db:
      build: db/
      container_name: postgres-phase2
      environment:
        - POSTGRES_PASSWORD=root
      ports:
        - 5432:5432
  
  phase2-server:
    build: server/
    container_name: phase2-server
    environment:
      - DB_HOST=postgres-phase2
    ports:
      - 5000:80