version: '3'

services:
  my-postgres-db:
      build: db/
      container_name: my-postgres-db
      environment:
        - POSTGRES_PASSWORD=root
      ports:
        - 5432:5432
  
  phase2-server:
    build: server/
    container_name: phase2-server
    environment:
      - HOST=my-postgres-db
    ports:
      - 5000:80