version: '3'

services:
  broker_1:
      build: pubsubserver/
      container_name: broker_1
      environment:
        - SERVER_LOCATION=appserver
        - SERVER_NAME=broker_1

      ports:
        - 8080:8080
  
  broker_2:
      build: pubsubserver/
      container_name: broker_2
      environment:
        - SERVER_LOCATION=appserver
        - SERVER_NAME=broker_2
      ports:
        - "8081:8080"
  
  broker_3:
      build: pubsubserver/
      container_name: broker_3
      environment:
        - SERVER_LOCATION=appserver
        - SERVER_NAME=broker_3
      ports:
        - "8082:8080"

  appserver:
    build: .
    container_name: appserver
    environment:
      - SERVER_LOCATION_1=broker_1
      - SERVER_LOCATION_2=broker_2
      - SERVER_LOCATION_3=broker_3
      - PORT_1=8080
      - PORT_2=8080
      - PORT_3=8080
    ports:
      - "3002:3000"
      - "5001:5001"